### ISSUE TITLE
v1.1.0 Snackbar not found Error

### ISSUE THREAD

**Issue by JoshDonnell** [modbender/nuxt-snackbar#21] opened 2024-07-28 22:50 UTC
**Describe the bug**
I have enchanted a bug with v1.1.0 where I get a fatal error of "Snackbar not found", this is when running Nuxt 3.12.4 with Nuxt 4 compatibility enabled, seems to error even when not running Nuxt 4 compatability mode as well.

**Reproduction**
https://stackblitz.com/edit/github-6tzif1?file=app%2Fapp.vue

**Comment by rahInoue** [comment] 2024-07-30 09:08
I encountered the same issue.
For now, downgrading Nuxt from version 3.12.4 to 3.12.3 resolved the problem.

**Comment by modbender** [comment] 2024-07-30 12:58
Oof, seems something broke in 3.12.4, I'll check it out.

**Comment by JoshDonnell** [comment] 2024-07-30 13:37
@modbender 

Thank you for taking a look, after having a very quick look it seems like the plugin isn't always registering, is that seems like the point of failure causing the error. Definitely a compatibility issue with Nuxt 3.12.4 in some strange way.

**Comment by modbender** [comment] 2024-07-30 13:53
@JoshDonnell actually this is weird, there's no breaking changes. 
If you check the playground https://stackblitz.com/github/modbender/nuxt-snackbar?file=playground%2Fapp.vue
it's totally working fine.
Just make sure you have `vue` installed in package.json

**Comment by JoshDonnell** [comment] 2024-07-30 14:07
@modbender 

No luck vue was installed on that StackBlitz, I added it as a dependency and installed it and still experienced the same error.

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, future, snackbar, modules
- Runtime Modules:  nuxt-snackbar@1.1.0
- Build Modules:    -
------------------------------

I set up the module locally and it runs great in the playground without error, it's an intermittent issue in my prod app as well.

I spent some time trying to debug the module to find the issue however I couldn't. It was more difficult as the playground worked perfectly on the module.

**Comment by rahInoue** [comment] 2024-07-30 23:07
My environment is as follows:

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4 
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools, build, css, postcss, plugins, modules, snackbar, ssr, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, @pinia/nuxt@0.5.2, nuxt-snackbar@1.1.0
- Build Modules:    
------------------------------

I encountered the same issue with the following steps:
- Start the nuxt app with `npm run dev` and access localhost
- Sometimes the snackbar works (about 1 in 30 times), but most of the time I get "Snackbar not found". Once this error occurs, it persists.
- The same error occurs even after reinstalling dependencies and rebooting the PC.
- The issue is resolved by downgrading Nuxt to version 3.12.3 in the same web app.

For the time being, downgrading Nuxt from version 3.12.4 to 3.12.3 resolved the problem.

**Comment by modbender** [comment] 2024-07-31 06:16
I actually have created a separate new Nuxt project to test this with v18.20.3 and it works fine so I think it's either Vue version or node version. But yeah this needs to be fixed for backward compatibility.

**Comment by JoshDonnell** [comment] 2024-07-31 07:57
@modbender 

Sadly this update has not resolved the issue for me, I don't think it's a node issue as on my local machine I am running v20.10.0 and am still experiencing the issue.

**Comment by JoshDonnell** [comment] 2024-07-31 08:05
@modbender 

After doing some digging there is a warning saying "injection "Symbol()" not found."

This corresponds to the Vue package powering their nuxt module in this file.

https://github.com/evo-mark/vue3-snackbar/blob/main/src/service.js

I have a feeling this is where the error is coming from as for some reason the Symbol is not being created. This only happens in Nuxt however running the Vue module on its own in Vue project works fine.

**Comment by modbender** [comment] 2024-08-03 09:47
@JoshDonnell could you try this last v1.1.2, I hope this might fix things.

**Comment by modbender** [comment] 2024-08-03 09:54
Also I think a node version upgrade might be necessary. I always use nvm for easy management.

**Comment by modbender** [comment] 2024-08-03 11:29
@JoshDonnell @rahInoue Digging through some old nuxt issues I found one of the fix was to delete .nuxt folder.

**Closed** 2024-08-05 09:14 UTC
Labels: question

**Comment by modbender** [comment] 2024-08-05 09:38
For future uses, the solution was to remove transpile on vue3-snackbar.
